- Add else ifeq statement to Makefile - Fix typo in dff2latch.v - Create "design" variable in specify_files_for_sdc.tcl

diff --git a/flow/Makefile b/flow/Makefile
--- a/flow/Makefile
+++ b/flow/Makefile
@@ -278,11 +278,12 @@ do-yosys: $(DONT_USE_SC_LIB)
 ifeq ($(MODE), default)
 	echo "Running default mode"
 	$(SCRIPTS_DIR)/synth.sh $(SYNTH_SCRIPT) $(LOG_DIR)/1_2_yosys.log
-endif
-
-ifeq ($(MODE), two_phase_clk)
+else ifeq ($(MODE), two_phase_clk)
 	echo "Running two-phase clocking with latches mode"
 	$(SCRIPTS_DIR)/synth.sh $(TWO_PHASE_CLK_SYNTH_SCRIPT) $(LOG_DIR)/1_2_yosys.log
+else
+	echo "Mode not recognized. Exiting with error code 1."
+	exit 1
 endif
 
 .PHONY: do-yosys-canonicalize
